services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  redisinsight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    environment:
      RI_REDIS_HOST: "redis"
      RI_REDIS_PORT: 6379
      RI_REDIS_USERNAME: default

  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "url_shortener"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "123"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: