DROP DATABASE IF EXISTS postgres;

CREATE TABLE IF NOT EXISTS urls (
    code VARCHAR(10) PRIMARY KEY,
    url TEXT NOT NULL,
    creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    clicks INTEGER DEFAULT 0
);
