database:
    db_address: localhost:5432
    db_user: user
    db_pass: 123
    db_name: postgres

http_server:
    address: localhost:3000
    timeout: 5s
    idle_timeout: 60s

redis:
    address: localhost:3001
    redis_user": user
    redis_password": 123
